[package]
name = "substrate-keystore"
version = "1.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
substrate-primitives = { path = "../primitives" }
crypto = { package = "parity-crypto", version = "0.3", default-features = false }
error-chain = "0.12.0"
hex = "0.3.2"
rand = "0.6.5"
serde_json = "1.0.39"
subtle = "2.1.0"

[dev-dependencies]
tempdir = "0.3.7"
