[package]
name = "substrate-telemetry"
version = "1.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Telemetry utils"
edition = "2018"

[dependencies]
parking_lot = "0.8.0"
lazy_static = "1.3.0"
log = "0.4.6"
rand = "0.6.5"
serde = { version = "1.0.91", features = ["derive"] }
serde_json = "1.0.39"
slog = { version = "2.4.1", features = ["nested-values"] }
slog-json = { version = "2.3.0", features = ["nested-values"] }
slog-async = { version = "2.3.0", features = ["nested-values"] }
slog-scope = "4.1.1"
ws = { version = "0.8.0", features = ["ssl"] }
