[package]
name = "substrate-consensus-slots"
version = "1.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Generic slots-based utilities for consensus"
edition = "2018"

[dependencies]
codec = { package = "parity-codec", version = "3.2" }
client = { package = "substrate-client", path = "../../client" }
primitives = { package = "substrate-primitives", path = "../../primitives" }
runtime_primitives = { package = "sr-primitives", path = "../../sr-primitives" }
consensus_common = { package = "substrate-consensus-common", path = "../common" }
inherents = { package = "substrate-inherents", path = "../../inherents" }
futures = "0.1.26"
tokio = "0.1.19"
parking_lot = "0.8.0"
error-chain = "0.12.0"
log = "0.4.6"
