[package]
name = "substrate-service"
version = "1.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
futures = "0.1.26"
parking_lot = "0.8.0"
error-chain = "0.12.0"
lazy_static = "1.3.0"
log = "0.4.6"
slog = { version = "2.4.1", features = ["nested-values"] }
tokio = "0.1.19"
exit-future = "0.1.4"
serde = { version = "1.0.91", features = ["derive"] }
serde_json = "1.0.39"
target_info = "0.1.0"
inherents = { package = "substrate-inherents", path = "../../core/inherents" }
keystore = { package = "substrate-keystore", path = "../../core/keystore" }
sr-io = { path = "../../core/sr-io" }
runtime_primitives = { package = "sr-primitives", path = "../../core/sr-primitives" }
primitives = { package = "substrate-primitives", path = "../../core/primitives" }
consensus_common = { package = "substrate-consensus-common", path = "../../core/consensus/common" }
network = { package = "substrate-network", path = "../../core/network" }
client = { package = "substrate-client", path = "../../core/client" }
client_db = { package = "substrate-client-db", path = "../../core/client/db" }
parity-codec = "3.5.1"
substrate-executor = { path = "../../core/executor" }
transaction_pool = { package = "substrate-transaction-pool", path = "../../core/transaction-pool" }
rpc = { package = "substrate-rpc-servers", path = "../../core/rpc-servers" }
tel = { package = "substrate-telemetry", path = "../../core/telemetry" }
offchain = { package = "substrate-offchain", path = "../../core/offchain" }

[dev-dependencies]
substrate-test-client = { path = "../test-client" }
