[package]
name = "srml-support-procedural"
version = "1.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
srml-support-procedural-tools = { path = "./tools" }
sr-api-macros = { path = "../../../core/sr-api-macros" }

proc-macro2 = "0.4.30"
quote = "0.6.12"
syn = { version = "0.15.34", features = ["full"] }
