[package]
name = "node-template"
version = "1.0.0"
authors = ["Anonymous"]
build = "build.rs"
edition = "2018"

[[bin]]
name = "node-template"
path = "src/main.rs"

[dependencies]
error-chain = "0.12.0"
futures = "0.1.26"
ctrlc = { version = "3.1.2", features = ["termination"] }
log = "0.4.6"
tokio = "0.1.19"
exit-future = "0.1.4"
parking_lot = "0.8.0"
parity-codec = "3.5.1"
trie-root = "0.12.2"
sr-io = { path = "../core/sr-io" }
substrate-cli = { path = "../core/cli" }
primitives = { package = "substrate-primitives", path = "../core/primitives" }
substrate-executor = { path = "../core/executor" }
substrate-service = { path = "../core/service" }
inherents = { package = "substrate-inherents", path = "../core/inherents" }
transaction-pool = { package = "substrate-transaction-pool", path = "../core/transaction-pool" }
network = { package = "substrate-network", path = "../core/network" }
consensus = { package = "substrate-consensus-aura", path = "../core/consensus/aura" }
substrate-client = {  path = "../core/client" }
basic-authorship = { package = "substrate-basic-authorship", path = "../core/basic-authorship" }
node-template-runtime = { path = "runtime" }

[build-dependencies]
vergen = "3.0.4"
