[package]
description = "libp2p implementation of the ethcore network library"
homepage = "http://parity.io"
license = "GPL-3.0"
name = "substrate-network-libp2p"
version = "1.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
byteorder = "1.3.1"
bytes = "0.4.12"
error-chain = { version = "0.12.0", default-features = false }
fnv = "1.0.6"
futures = "0.1.26"
libp2p = { version = "0.7.0", default-features = false, features = ["secio-secp256k1", "libp2p-websocket"] }
parking_lot = "0.8.0"
lazy_static = "1.3.0"
log = "0.4.6"
rand = "0.6.5"
serde = { version = "1.0.91", features = ["derive"] }
serde_json = "1.0.39"
smallvec = "0.6.9"
substrate-peerset = { path = "../peerset" }
tokio-io = "0.1.12"
tokio-timer = "0.2.10"
unsigned-varint = { version = "0.2.2", features = ["codec"] }
void = "1.0.2"

slog = { version = "2.4.1", features = ["nested-values"] }
slog_derive = "0.1.1"
erased-serde = "0.3.9"

[dev-dependencies]
tempdir = "0.3.7"
tokio = "0.1.19"
