[package]
name = "sr-primitives"
version = "1.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
num-traits = { version = "0.2.6", default-features = false }
integer-sqrt = "0.1.2"
serde = { version = "1.0.91", optional = true, features = ["derive"] }
parity-codec = { version = "3.5.1", default-features = false, features = ["derive"] }
substrate-primitives = { path = "../primitives", default-features = false }
rstd = { package = "sr-std", path = "../sr-std", default-features = false }
runtime_io = { package = "sr-io", path = "../sr-io", default-features = false }
log = { version = "0.4.6", optional = true }

[dev-dependencies]
serde_json = "1.0.39"

[features]
default = ["std"]
std = [
	"num-traits/std",
	"serde",
	"log",
	"rstd/std",
	"runtime_io/std",
	"parity-codec/std",
	"substrate-primitives/std",
]
